### PR TITLE
correct scrolling when selection range > visible range

### LINKED ISSUE #61: Cursor not visible at the bottom of a selection
## Steps to reproduce :

1. Open a long file
2. Use the command %
3. The anchor is no longer visible on screen, the view is locked on top of the selection

## Expected behavior

The anchor should always be visible

### PR DESCRIPTION
**Pull request by pomdtr**
Closes #61 

When the range of the selection was larger than the viewport, the revealRange command did scroll to the top of the selection, hiding the cursor. This pull request improves this behavior by making sure that the cursor is always visible.

### CODE REVIEW

File: src/commands/index.ts [hunk 1]
```diff
@@ -163,7 +163,8 @@ export class CommandDescriptor<Input extends InputKind = InputKind> {
 
     if (flags & CommandFlags.ChangeSelections) {
       // Scroll to cursor if needed
-      editor.revealRange(editor.selection)
+      let position = editor.selection.active
```
Comment (71) [inline src/commands/index.ts]:
```suggestion
      const position = editor.selection.active
```

**Comment by pomdtr** [comment]
Done !
